version: '3.8'

services:
  sigma:
    container_name: sigma
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "34998:34998"
    volumes:
      - sigma_data:/app/data
    environment:
      - SIGMA_ENV=production
      - SIGMA_PORT=34998
    restart: unless-stopped
    networks:
      - sigma_net

volumes:
  sigma_data:

networks:
  sigma_net:
