version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - ./data:/data/gnupg
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
