version: '3.8'

services:
  backend:
    build: ./backend
    environment:
    volumes:
      - ./data:/data/gnupg
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
